import React, {useEffect, useRef, useState} from 'react';
import { createRoot } from 'react-dom/client';
import {Camera, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Cloud, CloudOff, FileText, Home, MapPin, Plus, Share2, Signature, WandSparkles, X, AlertCircle, LoaderCircle} from 'lucide-react';
import './styles.css';
import {cloudAvailable, createCloudJob, listCloudJobs, saveCloudJob, uploadJobPhoto, type CloudJob} from './firebase';

type Step='dashboard'|'new'|'job'|'before'|'checklist'|'after'|'signature'|'summary'|'report';
type Job={customerName:string;phone:string;address:string;type:string;date:string;worker:string;memo:string};
const defaultJob:Job={customerName:'샘플 고객',phone:'010-1234-5678',address:'서울시 강남구 테헤란로 123',type:'정기청소',date:'2026-09-12 10:00',worker:'김작업',memo:'사무실 정기 청소 / 유리창 집중'};
const checklistByType:Record<string,string[]>={정기청소:['바닥','화장실','유리/창틀','주방','폐기물'],입주청소:['바닥','욕실','창틀/샷시','주방/후드','수납장','폐기물'],방역:['방역구역 확인','약제 확인','보호장비','약제 살포','환기/안전 확인'],기타:['작업 구역 확인','주요 작업','마감 확인','폐기물','고객 확인']};
const getChecklist=(t:string)=>checklistByType[t]||checklistByType.기타;
const nowLabel=()=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date());

function App(){
 const [step,setStep]=useState<Step>('dashboard'),[job,setJob]=useState<Job>(defaultJob),[before,setBefore]=useState<string[]>([]),[after,setAfter]=useState<string[]>([]),[checked,setChecked]=useState<Record<string,boolean>>({}),[signer,setSigner]=useState(''),[signature,setSignature]=useState(''),[signedAt,setSignedAt]=useState(''),[summary,setSummary]=useState(''),[notice,setNotice]=useState(''),[jobId,setJobId]=useState(''),[cloudJobs,setCloudJobs]=useState<CloudJob[]>([]),[busy,setBusy]=useState(false),[cloudError,setCloudError]=useState(''),[photoFallback,setPhotoFallback]=useState(()=>sessionStorage.getItem('m10_storage_disabled')==='1'),[online,setOnline]=useState(navigator.onLine);
 const items=getChecklist(job.type),completed=items.filter(x=>checked[x]).length;
 const progress=step==='job'?15:step==='before'?30:step==='checklist'?45:step==='after'?60:step==='signature'?75:step==='summary'?90:step==='report'?100:0;
 const go=(s:Step)=>{setNotice('');setStep(s)};
 useEffect(()=>{void refreshJobs()},[]);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 async function refreshJobs(){if(!cloudAvailable())return;try{setCloudError('');setCloudJobs(await listCloudJobs())}catch(e){setCloudError(e instanceof Error?e.message:'Firebase 목록을 불러오지 못했습니다.')}}
 const payload=(status:'진행 중'|'완료'='진행 중'):Omit<CloudJob,'id'|'createdAt'|'updatedAt'|'ownerUid'>=>({...job,checklist:checked,beforePhotos:before.filter(x=>!x.startsWith('data:')&&!x.startsWith('blob:')),afterPhotos:after.filter(x=>!x.startsWith('data:')&&!x.startsWith('blob:')),signer,signature,signedAt,summary,status});
 async function saveProgress(status:'진행 중'|'완료'='진행 중'){if(!cloudAvailable()||!jobId)return;try{setBusy(true);await saveCloudJob(jobId,payload(status));await refreshJobs()}catch(e){setCloudError(e instanceof Error?e.message:'Firebase 저장에 실패했습니다.')}finally{setBusy(false)}}
 async function createJob(){setChecked({});setBefore([]);setAfter([]);setSigner('');setSignature('');setSignedAt('');setSummary('');if(cloudAvailable()){try{setBusy(true);const id=await createCloudJob({...payload(),checklist:{},beforePhotos:[],afterPhotos:[],signer:'',signature:'',signedAt:'',summary:''});setJobId(id||'');await refreshJobs()}catch(e){setCloudError(e instanceof Error?e.message:'Firebase 현장 생성에 실패했습니다.')}finally{setBusy(false)}}else setJobId(`local-${Date.now()}`);go('job')}
 async function generateSummary(){if(!signer.trim()||!signature){setNotice('확인자 이름과 고객 서명을 모두 입력해주세요.');return}const done=items.filter(x=>checked[x]),text=[`[완료 작업]\n${done.length?done.join(' / '):'체크된 작업 없음'}`,`[특이사항]\n${job.memo.trim()||'특이사항 없음'}`,`[작업 증빙]\n작업 전 ${before.length}장 · 작업 후 ${after.length}장 사진 기록 완료`,`[고객 확인]\n${signer} 님 현장 확인 및 서명 완료 (${signedAt||nowLabel()})`,`[권장사항]\n다음 방문 시 동일 구역의 상태를 확인하고 필요한 경우 추가 작업을 진행합니다.`].join('\n\n');setSummary(text);go('summary');if(cloudAvailable()&&jobId){try{setBusy(true);await saveCloudJob(jobId,{...payload(),summary:text});await refreshJobs()}catch(e){setCloudError(e instanceof Error?e.message:'요약 저장에 실패했습니다.')}finally{setBusy(false)}}}
 async function uploadFiles(phase:'before'|'after',files:File[],setter:(v:string[])=>void,current:string[]){if(!files.length)return;setBusy(true);let usedFallback=false;const added:string[]=[];let disabled=photoFallback||sessionStorage.getItem('m10_storage_disabled')==='1';try{for(const f of files){if(cloudAvailable()&&jobId&&!disabled){try{added.push(await uploadJobPhoto(jobId,phase,f));continue}catch{usedFallback=true;disabled=true;sessionStorage.setItem('m10_storage_disabled','1')}}else usedFallback=true;added.push(await compressPhotoToDataUrl(f))}const merged=[...current,...added];setter(merged);if(usedFallback){setPhotoFallback(true);setNotice('Firebase Storage를 사용할 수 없어 사진을 기기에 임시 저장했습니다. 보고서 테스트는 그대로 진행할 수 있습니다.')}if(cloudAvailable()&&jobId){const cloudOnly=merged.filter(x=>!x.startsWith('data:')&&!x.startsWith('blob:'));await saveCloudJob(jobId,phase==='before'?{...payload(),beforePhotos:cloudOnly}:{...payload(),afterPhotos:cloudOnly});await refreshJobs()}}catch(e){setCloudError(e instanceof Error?e.message:'사진 처리에 실패했습니다.')}finally{setBusy(false)}}
 const statusLabel=cloudAvailable()?(photoFallback?'FIREBASE DB + LOCAL PHOTO · v0.4':'FIREBASE DB · v0.4'):'LOCAL MODE · v0.4';
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">M10</div><div><b>WORK PROOF</b><span>v0.4 · Mobile Field Test</span></div></div><nav><button onClick={()=>go('dashboard')}><Home/>오늘의 현장</button><button onClick={()=>go('new')}><Plus/>신규 현장</button><button onClick={()=>go('report')}><FileText/>보고서 미리보기</button></nav></aside><main><header><div><p>M10 PROJECT / MVP #001</p><h1>{title(step)}</h1></div><div className="status">{cloudAvailable()?<Cloud/>:<CloudOff/>}{statusLabel}</div></header>{!online&&<div className="notice error"><AlertCircle/>오프라인 상태입니다.</div>}<div className="mobileFieldBar"><span><b>모바일 현장 모드</b> · 카메라 촬영 · 손가락 서명 · 고객 공유</span><span className={online?'online':'offline'}>{online?'온라인':'오프라인'}</span></div>{progress>0&&<div className="progressWrap"><div className="progressTop"><span>작업 기록 진행률</span><b>{progress}%</b></div><div className="bar"><i style={{width:`${progress}%`}}/></div></div>}{notice&&<div className="notice"><AlertCircle/>{notice}</div>}{cloudError&&<div className="notice error"><AlertCircle/>Firebase: {cloudError}</div>}{busy&&<div className="syncBadge"><LoaderCircle className="spin"/>저장 처리 중</div>}<section>{render()}</section></main></div>;
 function render(){if(step==='dashboard')return <><div className="hero"><div><h2>현장에서 3분 안에<br/>작업 증빙을 끝내세요.</h2><p>사진·체크리스트·서명·고객용 보고서를 하나의 흐름으로 연결합니다.</p><button className="primary" onClick={()=>go('new')}><Plus/>신규 현장 등록</button></div><div className="metricGrid"><Metric n={String(cloudJobs.length)} t="저장된 현장"/><Metric n={String(cloudJobs.filter(x=>x.status==='진행 중').length)} t="진행 중"/><Metric n={String(cloudJobs.filter(x=>x.status==='완료').length)} t="완료"/></div></div></>;if(step==='new')return <Card title="신규 현장 등록"><Form job={job} setJob={j=>{if(j.type!==job.type)setChecked({});setJob(j)}}/><Footer next={createJob} label="현장 생성"/></Card>;if(step==='job')return <><div className="jobHero"><MapPin/><div><h2>{job.customerName}</h2><p>{job.address}</p></div></div><div className="flowGrid"><Flow t="1. 작업 전 사진" s={`${before.length}/10장`} on={()=>go('before')}/><Flow t="2. 체크리스트" s={`${completed}/${items.length} 완료`} on={()=>go('checklist')}/><Flow t="3. 작업 후 사진" s={`${after.length}/10장`} on={()=>go('after')}/><Flow t="4. 고객 서명" s={signature?'서명 완료':'미완료'} on={()=>go('signature')}/></div><button className="primary wide" onClick={generateSummary}><WandSparkles/>AI 작업요약 만들기</button></>;if(step==='before')return <PhotoStep title="작업 전 사진" photos={before} setPhotos={setBefore} upload={f=>uploadFiles('before',f,setBefore,before)} next={async()=>{if(!before.length){setNotice('작업 전 사진을 1장 이상 등록해주세요.');return}await saveProgress();go('checklist')}}/>;if(step==='checklist')return <Card title="작업 체크리스트"><div className="checklist">{items.map(k=><label className={checked[k]?'checked':''} key={k}><input type="checkbox" checked={!!checked[k]} onChange={e=>setChecked({...checked,[k]:e.target.checked})}/><CheckCircle2/>{k}</label>)}</div><Footer back={()=>go('before')} next={async()=>{await saveProgress();go('after')}} label="다음 단계"/></Card>;if(step==='after')return <PhotoStep title="작업 후 사진" photos={after} setPhotos={setAfter} upload={f=>uploadFiles('after',f,setAfter,after)} back={()=>go('checklist')} next={async()=>{if(!after.length){setNotice('작업 후 사진을 1장 이상 등록해주세요.');return}await saveProgress();go('signature')}}/>;if(step==='signature')return <Card title="고객 확인"><label className="field"><span>확인자 이름</span><input value={signer} onChange={e=>setSigner(e.target.value)}/></label><SignaturePad value={signature} onChange={v=>{setSignature(v);if(v)setSignedAt(nowLabel())}}/><Footer back={()=>go('after')} next={generateSummary} label="AI 작업요약 만들기"/></Card>;if(step==='summary')return <Card title="AI 작업요약"><textarea className="summaryArea" value={summary} onChange={e=>setSummary(e.target.value)}/><Footer back={()=>go('signature')} next={async()=>{await saveProgress();go('report')}} label="보고서 만들기"/></Card>;return <Report job={job} before={before} after={after} checked={checked} items={items} signer={signer} signature={signature} signedAt={signedAt} summary={summary} onBack={()=>go('summary')} onComplete={()=>saveProgress('완료')}/>}
}
const title=(s:Step)=>({dashboard:'오늘의 현장',new:'신규 현장 등록',job:'현장 작업 기록',before:'작업 전 사진',checklist:'체크리스트',after:'작업 후 사진',signature:'고객 확인',summary:'AI 작업요약',report:'작업 보고서'}[s]);
const Metric=({n,t}:{n:string,t:string})=><div className="metric"><strong>{n}</strong><span>{t}</span></div>;
const Card=({title,children}:{title:string,children:React.ReactNode})=><div className="card"><h2>{title}</h2>{children}</div>;
const Flow=({t,s,on}:{t:string,s:string,on:()=>void})=><button className="flow" onClick={on}><Camera/><b>{t}</b><span>{s}</span><ChevronRight/></button>;
const Form=({job,setJob}:{job:Job,setJob:(j:Job)=>void})=><div className="formGrid">{[['고객명','customerName'],['연락처','phone'],['주소','address'],['예정일/시간','date'],['담당자','worker']].map(([l,k])=><label className="field" key={k}><span>{l}</span><input value={job[k as keyof Job]} onChange={e=>setJob({...job,[k]:e.target.value})}/></label>)}<label className="field"><span>작업종류</span><select value={job.type} onChange={e=>setJob({...job,type:e.target.value})}>{Object.keys(checklistByType).map(x=><option key={x}>{x}</option>)}</select></label><label className="field full"><span>작업 메모</span><textarea value={job.memo} onChange={e=>setJob({...job,memo:e.target.value})}/></label></div>;
const Footer=({back,next,label}:{back?:()=>void,next:()=>void|Promise<void>,label:string})=><div className="footerBtns">{back&&<button className="ghost" onClick={back}><ChevronLeft/>이전</button>}<button className="primary" onClick={()=>void next()}>{label}<ChevronRight/></button></div>;
function PhotoStep({title,photos,setPhotos,next,back,upload}:{title:string,photos:string[],setPhotos:(x:string[])=>void,next:()=>void|Promise<void>,back?:()=>void,upload:(f:File[])=>void|Promise<void>}){const cam=useRef<HTMLInputElement>(null),gal=useRef<HTMLInputElement>(null);const add=(e:React.ChangeEvent<HTMLInputElement>)=>{void upload(Array.from(e.target.files||[]).slice(0,10-photos.length));e.target.value=''};return <Card title={title}><input ref={cam} hidden type="file" accept="image/*" capture="environment" onChange={add}/><input ref={gal} hidden type="file" accept="image/*" multiple onChange={add}/><div className="mobileCaptureGrid"><button className="capturePrimary" onClick={()=>cam.current?.click()}><Camera/><b>카메라로 촬영</b></button><button className="captureSecondary" onClick={()=>gal.current?.click()}><Plus/><b>앨범에서 선택</b></button></div><div className="photos">{photos.map((p,i)=><div className="photo" key={i}><img src={p}/><button onClick={()=>setPhotos(photos.filter((_,j)=>j!==i))}><X/></button></div>)}</div><Footer back={back} next={next} label="다음 단계"/></Card>}
function SignaturePad({value,onChange}:{value:string,onChange:(v:string)=>void}){const ref=useRef<HTMLCanvasElement>(null),drawing=useRef(false);const pos=(e:any,c:HTMLCanvasElement)=>{const r=c.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:(t.clientX-r.left)*(c.width/r.width),y:(t.clientY-r.top)*(c.height/r.height)}};const start=(e:any)=>{drawing.current=true;const c=ref.current!,p=pos(e,c),x=c.getContext('2d')!;x.beginPath();x.moveTo(p.x,p.y)};const move=(e:any)=>{if(!drawing.current)return;e.preventDefault();const c=ref.current!,p=pos(e,c),x=c.getContext('2d')!;x.lineWidth=3;x.lineCap='round';x.lineTo(p.x,p.y);x.stroke()};const end=()=>{if(!drawing.current)return;drawing.current=false;onChange(ref.current!.toDataURL('image/png'))};return <div className="signWrap"><canvas ref={ref} width={900} height={260} onMouseDown={start} onMouseMove={move} onMouseUp={end} onTouchStart={start} onTouchMove={move} onTouchEnd={end}/><small>{value?'서명이 저장되었습니다.':'손가락으로 서명하세요.'}</small></div>}
function Report({job,before,after,checked,items,signer,signature,signedAt,summary,onBack,onComplete}:any){const share=async()=>{const text=`[M10 WORK PROOF] ${job.customerName} 작업 완료\n${job.type} · ${job.date}\n\n${summary}`;if(navigator.share)await navigator.share({title:`${job.customerName} 작업 완료 보고`,text});else{await navigator.clipboard.writeText(text);alert('공유 내용이 복사되었습니다.')}};const pairs=Math.max(before.length,after.length,1);return <div className="reportShell"><div className="reportActions"><button className="ghost" onClick={onBack}>수정</button><button className="ghost" onClick={()=>print()}>PDF 저장/인쇄</button><button className="primary" onClick={()=>{void onComplete();void share()}}><Share2/>완료 저장 + 고객 공유</button></div><article className="report"><h2>{job.customerName} · {job.type}</h2><div className="reportMeta"><span>{job.address}</span><span>{job.date}</span><span>{job.worker}</span><span>{job.phone}</span></div><h3>BEFORE → AFTER</h3>{Array.from({length:pairs}).map((_,i)=><div className="compareRow" key={i}><figure>{before[i]?<img src={before[i]}/>:<div className="placeholder">사진 없음</div>}</figure><div className="arrow">→</div><figure>{after[i]?<img src={after[i]}/>:<div className="placeholder">사진 없음</div>}</figure></div>)}<h3>완료 체크리스트</h3><div className="reportChecks">{items.map((k:string)=><span className={checked[k]?'done':''} key={k}>{checked[k]?'✓':'○'} {k}</span>)}</div><h3>작업 결과 요약</h3><p className="preline">{summary}</p><h3>고객 확인</h3><div className="customerConfirm"><div><b>확인자</b> {signer}<br/><b>서명시각</b> {signedAt}</div>{signature&&<img className="signatureImage" src={signature}/>}</div></article></div>}
async function compressPhotoToDataUrl(file:File){const src=await fileToDataUrl(file),img=await loadImage(src),scale=Math.min(1,1280/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const x=c.getContext('2d');if(!x)return src;x.drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.72)}
const fileToDataUrl=(f:File)=>new Promise<string>((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=()=>rej(r.error);r.readAsDataURL(f)}),loadImage=(src:string)=>new Promise<HTMLImageElement>((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src});
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
